<!-- FLOCK EDIT <div id="top"></div> -->

<div class="header-container">
    <div class="header">
        <div class="header-left">
            <!-- FLOCK EDIT (removed logo) -->
        </div>
        <div class="header-center">

            <!-- LOGO -->
            <?php echo $this->getChildHtml('store_language') ?>         
            <?php if ($this->getIsHomePage()):?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>

            <!-- FLOCK EDIT (removed welcome msg and search bar) -->
  
        </div>        
        <div class="header-right">
        	<?php // echo $this->getChildHtml('store_switcher') ?>
            <!-- <div class="minicart">
                <?php // echo $this->getChildHtml('top_cart') ?>
            </div> -->
            <?php // echo $this->getChildHtml('currency') ?>  
            <!-- <div class="clear"></div> -->  
            <?php // echo $this->getChildHtml('topLinks') ?>  
        </div>      
    </div>
    <?php echo $this->getChildHtml('topMenu') ?>
    <?php echo $this->getChildHtml('topBread') ?>
    <?php echo $this->getChildHtml('topContainer'); ?>

</div>